import java.util.Scanner;

public class binaryno {
    public static void main(String[] args) {
        Scanner no = new Scanner(System.in);
        int num=no.nextInt();
        if(num%2==0) {
            
        }
        no.close();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    }
}
